export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
  },
  users: {
    profile: '/users/me/profile',
    profileById: (userId) => `/users/${userId}/profile`,
    avatar: '/users/me/avatar',
    avatarByUser: (userId) => `/users/${userId}/avatar`,
    groups: '/users/me/groups',
    notifications: '/users/me/notifications',
    notificationsUnreadCount: '/users/me/notifications/unread-count',
    notificationsReadAll: '/users/me/notifications/read-all',
    notificationRead: (notificationId) => `/users/me/notifications/${notificationId}/read`,
    myReliability: '/users/me/reliability',
    reliabilityByUser: (userId) => `/users/${userId}/reliability`,
  },
  onboarding: {
    profile: '/onboarding/profile',
  },
  matching: {
    findGroup: '/matching/find-group',
    job: (jobId) => `/matching/jobs/${jobId}`,
    byCourse: (courseCode) => `/matching/course/${courseCode}`,
  },
  admin: {
    cohorts: '/admin/cohorts',
    seedData: '/admin/seed',
    runMatching: '/admin/matching/run',
    groups: '/admin/groups',
    students: '/admin/students',
  },
  workspace: {
    byGroup: (groupId) => `/workspaces/${groupId}`,
    tasks: (groupId) => `/workspaces/${groupId}/tasks`,
    task: (groupId, taskId) => `/workspaces/${groupId}/tasks/${taskId}`,
    taskReorder: (groupId) => `/workspaces/${groupId}/tasks/reorder`,
    files: (groupId) => `/workspaces/${groupId}/files`,
    file: (groupId, fileId) => `/workspaces/${groupId}/files/${fileId}`,
    fileDownload: (groupId, fileId) => `/workspaces/${groupId}/files/${fileId}/download`,
    messages: (groupId) => `/workspaces/${groupId}/messages`,
    message: (groupId, messageId) => `/workspaces/${groupId}/messages/${messageId}`,
    messageAttachment: (groupId, messageId) =>
      `/workspaces/${groupId}/messages/${messageId}/attachment`,
    messageVoice: (groupId, messageId) => `/workspaces/${groupId}/messages/${messageId}/voice`,
    sessions: (groupId) => `/workspaces/${groupId}/sessions`,
    session: (groupId, sessionId) => `/workspaces/${groupId}/sessions/${sessionId}`,
  },
}
