export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
  },
  users: {
    profile: '/users/me/profile',
    profileById: (userId) => `/users/${userId}/profile`,
    avatar: '/users/me/avatar',
    avatarByUser: (userId) => `/users/${userId}/avatar`,
    groups: '/users/me/groups',
    notifications: '/users/me/notifications',
    notificationsUnreadCount: '/users/me/notifications/unread-count',
    notificationsReadAll: '/users/me/notifications/read-all',
    notificationRead: (notificationId) => `/users/me/notifications/${notificationId}/read`,
    myReliability: '/users/me/reliability',
    reliabilityByUser: (userId) => `/users/${userId}/reliability`,
  },
  onboarding: {
    profile: '/onboarding/profile',
  },
  matching: {
    findGroup: '/matching/find-group',
    job: (jobId) => `/matching/jobs/${jobId}`,
    byCourse: (courseCode) => `/matching/course/${courseCode}`,
    joinGroup: (groupId) => `/matching/groups/${groupId}/join`,
    leaveGroup: (groupId) => `/matching/groups/${groupId}/leave`,
  },
  admin: {
    dashboard: '/admin/dashboard',
    cohorts: '/admin/cohorts',
    seedData: '/admin/seed',
    runMatching: '/admin/matching/run',
    groups: '/admin/groups',
    group: (groupId) => `/admin/groups/${groupId}`,
    students: '/admin/students',
    student: (userId) => `/admin/students/${userId}`,
    users: '/admin/users',
    reports: {
      overview: '/admin/reports/overview',
      engagement: '/admin/reports/engagement',
      pods: '/admin/reports/pods',
      reliability: '/admin/reports/reliability',
      courses: '/admin/reports/courses',
      activity: '/admin/reports/activity',
    },
  },
  workspace: {
    byGroup: (groupId) => `/workspaces/${groupId}`,
    tasks: (groupId) => `/workspaces/${groupId}/tasks`,
    task: (groupId, taskId) => `/workspaces/${groupId}/tasks/${taskId}`,
    taskReorder: (groupId) => `/workspaces/${groupId}/tasks/reorder`,
    taskProgress: (groupId, taskId) => `/workspaces/${groupId}/tasks/${taskId}/progress`,
    taskRegressRequests: (groupId, taskId) =>
      `/workspaces/${groupId}/tasks/${taskId}/regress-requests`,
    taskRegressApprove: (groupId, taskId, requestId) =>
      `/workspaces/${groupId}/tasks/${taskId}/regress-requests/${requestId}/approve`,
    taskRegressReject: (groupId, taskId, requestId) =>
      `/workspaces/${groupId}/tasks/${taskId}/regress-requests/${requestId}/reject`,
    files: (groupId) => `/workspaces/${groupId}/files`,
    file: (groupId, fileId) => `/workspaces/${groupId}/files/${fileId}`,
    fileDownload: (groupId, fileId) => `/workspaces/${groupId}/files/${fileId}/download`,
    messages: (groupId) => `/workspaces/${groupId}/messages`,
    message: (groupId, messageId) => `/workspaces/${groupId}/messages/${messageId}`,
    messageAttachment: (groupId, messageId) =>
      `/workspaces/${groupId}/messages/${messageId}/attachment`,
    messageVoice: (groupId, messageId) => `/workspaces/${groupId}/messages/${messageId}/voice`,
    sessions: (groupId) => `/workspaces/${groupId}/sessions`,
    session: (groupId, sessionId) => `/workspaces/${groupId}/sessions/${sessionId}`,
    activeCall: (groupId) => `/workspaces/${groupId}/calls/active`,
    calls: (groupId) => `/workspaces/${groupId}/calls`,
    call: (groupId, callId) => `/workspaces/${groupId}/calls/${callId}`,
    callJoin: (groupId, callId) => `/workspaces/${groupId}/calls/${callId}/join`,
    callLeave: (groupId, callId) => `/workspaces/${groupId}/calls/${callId}/leave`,
    callEnd: (groupId, callId) => `/workspaces/${groupId}/calls/${callId}/end`,
  },
}
